-- users
create table public.users (
  id bigint generated by default as identity not null,
  name text null,
  email text null,
  password text null,
  favorites text[] null,
  constraint users_pkey primary key (id)
) TABLESPACE pg_default;