-- users
create table public.users (
  id bigint generated by default as identity not null,
  name text null,
  email text null,
  password text null,
  created_at timestamp with time zone null default now(),
  favorites bigint[] null,
  constraint users_pkey primary key (id)
) TABLESPACE pg_default;

--favorites
create table public.favorites (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null default 'favorites'::text,
  description text null,
  plants text[] null,
  constraint favorites_pkey primary key (id)
) TABLESPACE pg_default;

--user-favorites-list
create table public.user_favorites_list (
  user_id bigint generated by default as identity not null,
  favorites_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint user_favorites_list_pkey primary key (user_id, favorites_id)
) TABLESPACE pg_default;

--plants
create table public.plants (
  id bigint generated by default as identity not null,
  name text null,
  kcal bigint null default '0'::bigint,
  fat double precision null default '0'::double precision,
  sodium double precision null default '0'::double precision,
  carbohydrates double precision null default '0'::double precision,
  fiber double precision null default '0'::double precision,
  sugars double precision null default '0'::double precision,
  protein double precision null default '0'::double precision,
  calcium double precision null default '0'::double precision,
  potassium double precision null default '0'::double precision,
  magnesium double precision null default '0'::double precision,
  vitamin_c double precision null default '0'::double precision,
  growth_time bigint null default '0'::bigint,
  locations text[] null,
  constraint Plants_pkey primary key (id)
) TABLESPACE pg_default;